-- Grant all permissions to megastore_user
GRANT USAGE, CREATE ON SCHEMA public TO megastore_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO megastore_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO megastore_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO megastore_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO megastore_user;
